### ISSUE TITLE
Docker compose Example?

### ISSUE THREAD

**Issue by killmasta93** [vbkunin/itop-docker#38]
Hi
I was wondering if you have an example of a docker compose?
I currently have this but not sure if  the files how would i add it the bind the volumes?

Thank you 
```

version: '3'
services:
  itop:
    image: vbkunin/itop
    restart: always
    ports:
      - "3003:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=itop
      - DB_USER=root
      - DB_PASSWORD=secret
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=itop
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

volumes:
  db_data:
    driver: local-persist
    driver_opts:
     mountpoint: /scsi2/itop
```

**Comment by vbkunin** [comment]
```
name: "itop"

services:
  itop-app:
    image: vbkunin/itop:latest-base
    ports:
      - "8000:80"
    networks:
      - itop-net
    volumes:
      - ./itop/conf:/var/www/html/conf
      - ./itop/extensions:/var/www/html/extensions
      - ./apache2/alias.conf:/etc/apache2/conf-enabled/alias.conf
      - ./apache2/security.conf:/etc/apache2/conf-enabled/security-itop.conf
      - ./apache2/headers.load:/etc/apache2/mods-enabled/headers.load
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    networks:
      - itop-net
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb/conf.d/low-memory.cnf:/etc/mysql/conf.d/low-memory.cnf
      - ./mariadb/conf.d/90-bind-address.cnf:/etc/mysql/mariadb.conf.d/90-bind-address.cnf
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    command: --bind-address=0.0.0.0

volumes:
  mariadb-data:

networks:
  itop-net:
```
